apiVersion: skaffold/v1alpha4
kind: Config
build:
  artifacts:
  - image: qeek-dev/vote-app
    context: ./vote
    docker:
      dockerfile: Dockerfile
  - image: qeek-dev/vote-result
    context: ./result
    docker:
      dockerfile: Dockerfile
  - image: qeek-dev/vote-worker
    context: ./worker
    docker:
      dockerfile: Dockerfile
deploy:
  # kubectl:
  #   manifests:
  #   - postgres/deployment.yaml
  #   - redis/deployment.yaml
  #   - result/deployment.yaml
  #   - vote/deployment.yaml
  #   - worker/deployment.yaml
  helm:
    releases:
    - name: voting-app
      chartPath: vote-app
      namespace: default
      values:
        appImage: qeek-dev/vote-app
        resultImage: qeek-dev/vote-result
        workerImage: qeek-dev/vote-worker
