apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-postgres
  template:
    metadata:
      labels:
        app: vote-postgres
    spec:
      containers:
      - name: vote-postgres-pod
        image: postgres:9.4
        env:
        - name: POSTGRES_DB
          value: "postgres"
        - name: POSTGRES_USER
          value: "postgres_user"
        - name: POSTGRES_PASSWORD
          value: "postgres_password"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote-postgres-service
  name: db
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: vote-postgres
  type: NodePort
status:
  loadBalancer: {}
