apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-redis
  template:
    metadata:
      labels:
        app: vote-redis
    spec:
      containers:
      - name: vote-redis-pod
        image: redis:alpine
        command: ["redis-server"]
        args: ["--requirepass", "redis_password"]
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote-redis-service
  name: redis
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: vote-redis
  type: NodePort
status:
  loadBalancer: {}
