apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-worker
  template:
    metadata:
      labels:
        app: vote-worker
    spec:
      containers:
      - name: vote-worker-pod
        image: qeek-dev/vote-worker
